// Generated by CoffeeScript 1.3.3
(function() {

  window.App = Ember.Application.create();

  App.Store = DS.Store.extend({
    revision: 12,
    adapter: 'DS.FixtureAdapter'
  });

  App.Router.map(function() {
    this.resource("home");
    this.resource("about");
    this.resource("lessons", {
      path: "lessons"
    });
    return this.resource("lessonshow", {
      path: "lessonshow/:lesson_id"
    });
  });

  App.LessonsRoute = Ember.Route.extend({
    model: function() {
      return App.Lesson.find();
    }
  });

  App.HomeRoute = Ember.Route.extend({
    model: function() {
      return App.Lesson.find();
    }
  });

  App.Lesson = DS.Model.extend({
    title: DS.attr('string'),
    summary: DS.attr('string'),
    imageUrl: DS.attr('string'),
    createdAt: DS.attr('date'),
    mp3: DS.attr('sring')
  });

  Ember.Handlebars.registerBoundHelper('date', function(date) {
    return moment(date).fromNow();
  });

  App.Lesson.FIXTURES = [
    {
      id: 1,
      title: "Crying out to God",
      summary: "A studie in psalms of King David seeking God.",
      imageUrl: "/images/crying_out_to_god.jpg",
      createdAt: new Date('12-22-2012'),
      mp3: "/mp3/1.mp3"
    }, {
      id: 2,
      title: "Into the belly of the whale",
      summary: "A studie in psalms of King David seeking God.",
      imageUrl: "/images/crying_out_to_god.jpg",
      createdAt: new Date('12-22-2012'),
      mp3: "/mp3/1.mp3"
    }, {
      id: 3,
      title: "Jeremiah gets down",
      summary: "A studie in psalms of King David seeking God.",
      imageUrl: "/images/crying_out_to_god.jpg",
      createdAt: new Date('12-22-2012'),
      mp3: "/mp3/1.mp3"
    }, {
      id: 4,
      title: "Crying out to God",
      summary: "A studie in psalms of King David seeking God.",
      imageUrl: "/images/crying_out_to_god.jpg",
      createdAt: new Date('12-22-2012'),
      mp3: "/mp3/1.mp3"
    }, {
      id: 5,
      title: "Crying out to God",
      summary: "A studie in psalms of King David seeking God.",
      imageUrl: "/images/crying_out_to_god.jpg",
      createdAt: new Date('12-22-2012'),
      mp3: "/mp3/1.mp3"
    }, {
      id: 6,
      title: "Crying out to God",
      summary: "A studie in psalms of King David seeking God.",
      imageUrl: "/images/crying_out_to_god.jpg",
      createdAt: new Date('12-22-2012'),
      mp3: "/mp3/1.mp3"
    }, {
      id: 7,
      title: "Crying out to God",
      summary: "A studie in psalms of King David seeking God.",
      imageUrl: "/images/crying_out_to_god.jpg",
      createdAt: new Date('12-22-2012'),
      mp3: "/mp3/1.mp3"
    }, {
      id: 8,
      title: "Crying out to God",
      summary: "A studie in psalms of King David seeking God.",
      imageUrl: "/images/crying_out_to_god.jpg",
      createdAt: new Date('12-22-2012'),
      mp3: "/mp3/1.mp3"
    }
  ];

  $(function() {
    return $(document).on("click", ".play_button", function() {
      var $button, audioPlayer, mediaPath;
      audioPlayer = $("#lesson_mod_menu");
      console.log(audioPlayer);
      audioPlayer.css({
        display: 'block'
      });
      $button = $(this);
      mediaPath = $button.text();
      window.player = $("#jquery_jplayer_1").jPlayer({
        swfPath: "http://jplayer.org/latest/js",
        supplied: "mp3, oga",
        ready: function() {
          player.bind($.jPlayer.event.play, function() {
            console.log("play event");
            return $button.removeClass("paused");
          });
          return player.bind($.jPlayer.event.pause, function() {
            console.log("pause event");
            return $button.addClass("paused");
          });
        }
      });
      if ($button.data("state") === "playing") {
        console.log("clicked pause");
        player.jPlayer("pause");
        return $button.data("state", "paused");
      } else {
        console.log("clicked play");
        player.jPlayer("setMedia", {
          mp3: mediaPath
        });
        player.jPlayer("play");
        $button.data("state", "playing");
        return $button.removeClass("paused");
      }
    });
  });

}).call(this);
