// Generated by CoffeeScript 1.3.3
(function() {

  window.App = Ember.Application.create();

  App.Router.map(function() {});

  App.IndexRoute = Ember.Route.extend({
    model: function() {
      return ['red', 'yellow', 'blue'];
    }
  });

}).call(this);
